version: '3'
services:
    ms-sql-server:
        image: justin2004/mssql_server_tiny
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Passw0rd2020"
            MSSQL_PID: "Express"
        ports: 
            - "1433:1433"
    colour-api:
        build: .
        environment: 
            DBServer: "ms-sql-server"
        ports:
            - "8080:80"